name: ngi_api
description: The interface and models for an API providing access to assets.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  hive  : ^2.2.3
  http: ^0.13.5
  json_annotation: ^4.6.0
  logger: ^1.1.0
  meta: ^1.7.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.21.1
  very_good_analysis: ^3.0.1
